### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by mmbarness** [mmbarness/recordcollector#5]
# Database Schema
- [x] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [ ] primary key
    - [ ] not null
    - [ ] unique
    - [ ] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
---

**Comment by iProgYou** [comment]
- You didn't really follow the bluebird format, but we can possibly make this work
- If you want to track track purchases you will need a separate table. having one foreign key in the users table won't work
